Import("env")
env = env.Clone()

directory = Dir('.').srcnode().path
docker_name = 'exploire/' + directory.replace('/', '_')

service = env.Program(target="bin/service", source=Glob("*.c"), LIBS=["m"])

docker_build = env.Command(target=".docker-built",
                           source="bin/service",
                           action="docker build -t {docker_name} {directory} > $TARGET"
                           .format(docker_name=docker_name, directory=directory))

env.Depends(docker_build, service)
